server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/auth/**, /users/**
        - id: donor-service
          uri: ${DONOR_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/donors/**
        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/inventory/**
        - id: request-service
          uri: ${REQUEST_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/requests/**
        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/notify/**
