server:
  port: 8082
spring:
  application:
    name: donor-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/blood_bank_db?currentSchema=donor_schema}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: donor_schema
